name: Rust

on:
  push:
    branches: [ master ]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          default: true
          override: true
    
      - name: build
        run: cargo build --all --release

      - name: release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/timetabling-buddy.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-mac:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          default: true
          override: true
      - name: build
        run: cargo build --all --release && strip target/release/timetabling-buddy && mv target/release/timetabling-buddy target/release/timetabling-buddy-darwin
        
      - name: release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/timetabling-buddy-darwin
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
